### PR TITLE
add simplejson backend

### LINKED ISSUE #3: tuples and lists are converted to same json code
To make tuples have a unique representation, I used
```
def __serialize_tuple(c):
    print('tuple!')
    return serialize_module.dumps(c)

def __unserialize_tuple(s):
    return tuple(serialize_module.loads(s)) 

fmt = 'json'
serialize_module.register_class(tuple, __serialize_tuple, __unserialize_tuple)

print(serialize_module.dumps( [1,2], fmt ) )
print(serialize_module.dumps( (1,2), fmt ) )
```
But this has no effect.

### PR DESCRIPTION
**Pull request by peendebak**
* Add simplejson backend. The parameter `tuple_to_array` is set to False to fix #3 
* Add version information to module

@hgrecco Is there an option to pass parameters to the backend? This would allow to make `tuple_to_array` configurable.

### CODE REVIEW

**Comment by hgrecco** [comment]
I would like to merge it but tests are failing.

**Comment by peendebak** [comment]
@hgrecco Nested tuples are hard to get right, so I had to slightly modify the `all.py`. Tests should pass now

**Comment by hgrecco** [comment]
Have you tried using `all.traverse_and_decode`?

**Comment by peendebak** [comment]
Superseded by #5

**Pull request closed without merging**
